import os


DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

SIMULATION_DT_SECONDS = 1.0
HISTORIAN_DB = "distillation_history.sqlite"

PRESSURE_HIGH = 125.0
PRESSURE_HIGH_HIGH = 140.0
FEED_TANK_LOW_LOW = 10.0
BOTTOM_LOW_LOW = 15.0
REFLUX_DRUM_HIGH_HIGH = 85.0

TOP_TEMP_SETPOINT = 79.0
BOTTOM_TEMP_SETPOINT = 100.0
PRESSURE_SETPOINT = 105.0
REFLUX_DRUM_LEVEL_SETPOINT = 50.0
BOTTOM_LEVEL_SETPOINT = 55.0
